name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker_image_demo
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 442803386520.dkr.ecr.ap-south-1.amazonaws.com
        docker build . --file docker/Dockerfile --tag myimage:latest
        docker tag myimage:latest 442803386520.dkr.ecr.ap-south-1.amazonaws.com/myimage:latest
        docker push 442803386520.dkr.ecr.ap-south-1.amazonaws.com/myimage:latest
